/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaterialsRouteRouteImport } from './routes/materials/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LectureIdRouteImport } from './routes/lecture.$id'
import { Route as MaterialsIdRouteRouteImport } from './routes/materials/$id/route'
import { Route as MaterialsIdIndexRouteImport } from './routes/materials/$id/index'
import { Route as MaterialsIdEditRouteImport } from './routes/materials/$id/edit'
import { Route as MaterialsIdAddRouteImport } from './routes/materials/$id/add'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRouteRoute = MaterialsRouteRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureIdRoute = LectureIdRouteImport.update({
  id: '/lecture/$id',
  path: '/lecture/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsIdRouteRoute = MaterialsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MaterialsRouteRoute,
} as any)
const MaterialsIdIndexRoute = MaterialsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaterialsIdRouteRoute,
} as any)
const MaterialsIdEditRoute = MaterialsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MaterialsIdRouteRoute,
} as any)
const MaterialsIdAddRoute = MaterialsIdAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => MaterialsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/materials': typeof MaterialsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/materials/$id': typeof MaterialsIdRouteRouteWithChildren
  '/lecture/$id': typeof LectureIdRoute
  '/materials/$id/add': typeof MaterialsIdAddRoute
  '/materials/$id/edit': typeof MaterialsIdEditRoute
  '/materials/$id/': typeof MaterialsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/materials': typeof MaterialsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/lecture/$id': typeof LectureIdRoute
  '/materials/$id/add': typeof MaterialsIdAddRoute
  '/materials/$id/edit': typeof MaterialsIdEditRoute
  '/materials/$id': typeof MaterialsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/materials': typeof MaterialsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/materials/$id': typeof MaterialsIdRouteRouteWithChildren
  '/lecture/$id': typeof LectureIdRoute
  '/materials/$id/add': typeof MaterialsIdAddRoute
  '/materials/$id/edit': typeof MaterialsIdEditRoute
  '/materials/$id/': typeof MaterialsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/materials'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/materials/$id'
    | '/lecture/$id'
    | '/materials/$id/add'
    | '/materials/$id/edit'
    | '/materials/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/materials'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/lecture/$id'
    | '/materials/$id/add'
    | '/materials/$id/edit'
    | '/materials/$id'
  id:
    | '__root__'
    | '/'
    | '/materials'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/materials/$id'
    | '/lecture/$id'
    | '/materials/$id/add'
    | '/materials/$id/edit'
    | '/materials/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaterialsRouteRoute: typeof MaterialsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  LectureIdRoute: typeof LectureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture/$id': {
      id: '/lecture/$id'
      path: '/lecture/$id'
      fullPath: '/lecture/$id'
      preLoaderRoute: typeof LectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/$id': {
      id: '/materials/$id'
      path: '/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof MaterialsIdRouteRouteImport
      parentRoute: typeof MaterialsRouteRoute
    }
    '/materials/$id/': {
      id: '/materials/$id/'
      path: '/'
      fullPath: '/materials/$id/'
      preLoaderRoute: typeof MaterialsIdIndexRouteImport
      parentRoute: typeof MaterialsIdRouteRoute
    }
    '/materials/$id/edit': {
      id: '/materials/$id/edit'
      path: '/edit'
      fullPath: '/materials/$id/edit'
      preLoaderRoute: typeof MaterialsIdEditRouteImport
      parentRoute: typeof MaterialsIdRouteRoute
    }
    '/materials/$id/add': {
      id: '/materials/$id/add'
      path: '/add'
      fullPath: '/materials/$id/add'
      preLoaderRoute: typeof MaterialsIdAddRouteImport
      parentRoute: typeof MaterialsIdRouteRoute
    }
  }
}

interface MaterialsIdRouteRouteChildren {
  MaterialsIdAddRoute: typeof MaterialsIdAddRoute
  MaterialsIdEditRoute: typeof MaterialsIdEditRoute
  MaterialsIdIndexRoute: typeof MaterialsIdIndexRoute
}

const MaterialsIdRouteRouteChildren: MaterialsIdRouteRouteChildren = {
  MaterialsIdAddRoute: MaterialsIdAddRoute,
  MaterialsIdEditRoute: MaterialsIdEditRoute,
  MaterialsIdIndexRoute: MaterialsIdIndexRoute,
}

const MaterialsIdRouteRouteWithChildren =
  MaterialsIdRouteRoute._addFileChildren(MaterialsIdRouteRouteChildren)

interface MaterialsRouteRouteChildren {
  MaterialsIdRouteRoute: typeof MaterialsIdRouteRouteWithChildren
}

const MaterialsRouteRouteChildren: MaterialsRouteRouteChildren = {
  MaterialsIdRouteRoute: MaterialsIdRouteRouteWithChildren,
}

const MaterialsRouteRouteWithChildren = MaterialsRouteRoute._addFileChildren(
  MaterialsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaterialsRouteRoute: MaterialsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  LectureIdRoute: LectureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
