// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const archiveCollection = `-- name: ArchiveCollection :execrows
UPDATE collections
SET archived_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND archived_at IS NULL
`

type ArchiveCollectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveCollection(ctx context.Context, arg ArchiveCollectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveCollection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections(id, user_id, title, description)
    VALUES($1, $2, $3, $4)
RETURNING id, user_id, title, description, created_at, updated_at, archived_at
`

type CreateCollectionParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAllArchivedCollections = `-- name: GetAllArchivedCollections :many
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE user_id = $1
  AND archived_at IS NOT NULL
ORDER BY archived_at DESC
LIMIT 20
`

func (q *Queries) GetAllArchivedCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getAllArchivedCollections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCollections = `-- name: GetAllCollections :many
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE user_id = $1
  AND archived_at IS NULL
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) GetAllCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getAllCollections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUnarchivedCollections = `-- name: GetAllUnarchivedCollections :many
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE user_id = $1
  AND archived_at IS NULL
ORDER BY archived_at DESC
LIMIT 20
`

func (q *Queries) GetAllUnarchivedCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getAllUnarchivedCollections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedCollectionByID = `-- name: GetArchivedCollectionByID :one
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE id = $1
  AND user_id = $2
  AND archived_at IS NOT NULL
`

type GetArchivedCollectionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetArchivedCollectionByID(ctx context.Context, arg GetArchivedCollectionByIDParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getArchivedCollectionByID, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE id = $1
  AND user_id = $2
  AND archived_at IS NULL
`

type GetCollectionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCollectionByID(ctx context.Context, arg GetCollectionByIDParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByID, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCollectionsCount = `-- name: GetCollectionsCount :one
SELECT count(*)
FROM collections
WHERE user_id = $1
`

func (q *Queries) GetCollectionsCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCollectionsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unarchiveCollection = `-- name: UnarchiveCollection :execrows
UPDATE collections
SET archived_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE collections.id = $1
  AND collections.user_id = $2
  AND collections.archived_at IS NOT NULL
  AND (
      SELECT COUNT(*)
      FROM collections AS active
      WHERE active.user_id = collections.user_id
        AND active.archived_at IS NULL
  ) < 20
`

type UnarchiveCollectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnarchiveCollection(ctx context.Context, arg UnarchiveCollectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unarchiveCollection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCollectionDescription = `-- name: UpdateCollectionDescription :one
UPDATE collections
    SET description = $1,
    updated_at = CURRENT_TIMESTAMP
    WHERE id = $2 AND user_id = $3
RETURNING id, user_id, title, description, created_at, updated_at, archived_at
`

type UpdateCollectionDescriptionParams struct {
	Description string    `json:"description"`
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateCollectionDescription(ctx context.Context, arg UpdateCollectionDescriptionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, updateCollectionDescription, arg.Description, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateCollectionTitle = `-- name: UpdateCollectionTitle :one
UPDATE collections
    SET title = $1,
    updated_at = CURRENT_TIMESTAMP
    WHERE id = $2 AND user_id = $3
RETURNING id, user_id, title, description, created_at, updated_at, archived_at
`

type UpdateCollectionTitleParams struct {
	Title  string    `json:"title"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateCollectionTitle(ctx context.Context, arg UpdateCollectionTitleParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, updateCollectionTitle, arg.Title, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
