// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flashcards.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createFlashcard = `-- name: CreateFlashcard :exec
INSERT INTO flashcards (id, material_id, front, back)
SELECT $1, $2, $3, $4
WHERE EXISTS (
    SELECT 1
    FROM materials m
    JOIN collections c ON c.id = m.collection_id
    WHERE m.id = $2 AND c.user_id = $5
)
`

type CreateFlashcardParams struct {
	ID         uuid.UUID `json:"id"`
	MaterialID uuid.UUID `json:"material_id"`
	Front      string    `json:"front"`
	Back       string    `json:"back"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateFlashcard(ctx context.Context, arg CreateFlashcardParams) error {
	_, err := q.db.ExecContext(ctx, createFlashcard,
		arg.ID,
		arg.MaterialID,
		arg.Front,
		arg.Back,
		arg.UserID,
	)
	return err
}

const getOldestFlashcard = `-- name: getOldestFlashcard :one
SELECT f.id, f.material_id, f.front, f.back, f.created_at, f.updated_at, f.last_used
FROM flashcards f
JOIN materials m ON m.id = f.material_id
JOIN collections c ON c.id = m.collection_id
WHERE c.user_id = $1
ORDER BY f.last_used ASC
LIMIT 1
`

func (q *Queries) getOldestFlashcard(ctx context.Context, userID uuid.UUID) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, getOldestFlashcard, userID)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Front,
		&i.Back,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsed,
	)
	return i, err
}

const useFlashcard = `-- name: useFlashcard :execrows
UPDATE flashcards
	SET last_used = NOW()
	WHERE id = $1
`

func (q *Queries) useFlashcard(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, useFlashcard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
