// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flashcards.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFlashcard = `-- name: CreateFlashcard :exec
INSERT INTO flashcards (id, material_id, front, back)
SELECT $1, $2, $3, $4
WHERE EXISTS (
    SELECT 1
    FROM materials m
    JOIN collections c ON c.id = m.collection_id
    WHERE m.id = $2 AND c.user_id = $5
)
`

type CreateFlashcardParams struct {
	ID         uuid.UUID `json:"id"`
	MaterialID uuid.UUID `json:"material_id"`
	Front      string    `json:"front"`
	Back       string    `json:"back"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateFlashcard(ctx context.Context, arg CreateFlashcardParams) error {
	_, err := q.db.ExecContext(ctx, createFlashcard,
		arg.ID,
		arg.MaterialID,
		arg.Front,
		arg.Back,
		arg.UserID,
	)
	return err
}

const deleteFlashcard = `-- name: DeleteFlashcard :one
DELETE FROM flashcards f
WHERE f.id = $1
  AND material_id IN (
    SELECT m.id
    FROM materials m
    JOIN collections c ON c.id = m.collection_id
    WHERE c.user_id = $2
  )
RETURNING f.id
`

type DeleteFlashcardParams struct {
	FlashcardID uuid.UUID `json:"flashcard_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteFlashcard(ctx context.Context, arg DeleteFlashcardParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteFlashcard, arg.FlashcardID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getFlashcardsPage = `-- name: GetFlashcardsPage :many
SELECT f.id, f.material_id, f.front, f.back, f.created_at, f.updated_at, f.last_used, m.title AS material_title
FROM flashcards f
JOIN materials m ON m.id = f.material_id
JOIN collections c ON c.id = m.collection_id
WHERE c.user_id = $1 AND f.id < $2
ORDER BY f.id DESC
LIMIT 20
`

type GetFlashcardsPageParams struct {
	UserID              uuid.UUID `json:"user_id"`
	LastSeenFlashcardID uuid.UUID `json:"last_seen_flashcard_id"`
}

type GetFlashcardsPageRow struct {
	ID            uuid.UUID `json:"id"`
	MaterialID    uuid.UUID `json:"material_id"`
	Front         string    `json:"front"`
	Back          string    `json:"back"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	LastUsed      time.Time `json:"last_used"`
	MaterialTitle string    `json:"material_title"`
}

func (q *Queries) GetFlashcardsPage(ctx context.Context, arg GetFlashcardsPageParams) ([]GetFlashcardsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getFlashcardsPage, arg.UserID, arg.LastSeenFlashcardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlashcardsPageRow
	for rows.Next() {
		var i GetFlashcardsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.Front,
			&i.Back,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsed,
			&i.MaterialTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlashcard = `-- name: UpdateFlashcard :one
UPDATE flashcards
SET 
    front = CASE WHEN $1 <> '' THEN $1 ELSE front END,
    back  = CASE WHEN $2  <> '' THEN $2  ELSE back  END,
    updated_at = CURRENT_TIMESTAMP
FROM materials m
JOIN collections c ON c.id = m.collection_id
WHERE flashcards.material_id = m.id
  AND flashcards.id = $3
  AND c.user_id = $4
RETURNING flashcards.id, flashcards.material_id, flashcards.front, flashcards.back, flashcards.created_at, flashcards.updated_at, flashcards.last_used
`

type UpdateFlashcardParams struct {
	Front       interface{} `json:"front"`
	Back        interface{} `json:"back"`
	FlashcardID uuid.UUID   `json:"flashcard_id"`
	UserID      uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateFlashcard(ctx context.Context, arg UpdateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, updateFlashcard,
		arg.Front,
		arg.Back,
		arg.FlashcardID,
		arg.UserID,
	)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Front,
		&i.Back,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsed,
	)
	return i, err
}

const getOldestFlashcard = `-- name: getOldestFlashcard :one
SELECT f.id, f.material_id, f.front, f.back, f.created_at, f.updated_at, f.last_used
FROM flashcards f
JOIN materials m ON m.id = f.material_id
JOIN collections c ON c.id = m.collection_id
WHERE c.user_id = $1
ORDER BY f.last_used ASC
LIMIT 1
`

func (q *Queries) getOldestFlashcard(ctx context.Context, userID uuid.UUID) (Flashcard, error) {
	row := q.db.QueryRowContext(ctx, getOldestFlashcard, userID)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Front,
		&i.Back,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsed,
	)
	return i, err
}

const useFlashcard = `-- name: useFlashcard :execrows
UPDATE flashcards
	SET last_used = NOW()
	WHERE id = $1
`

func (q *Queries) useFlashcard(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, useFlashcard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
