// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_flashcards.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createImageFlashcard = `-- name: createImageFlashcard :one
INSERT INTO image_flashcards (id, material_id, title, image_key, image_size)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (
    SELECT 1
    FROM materials m
    JOIN collections c ON c.id = m.collection_id
    WHERE m.id = $2 AND c.user_id = $6
)
RETURNING image_flashcards.id, image_flashcards.material_id, image_flashcards.title, image_flashcards.image_key, image_flashcards.image_size, image_flashcards.created_at, image_flashcards.updated_at, image_flashcards.last_used
`

type createImageFlashcardParams struct {
	ID         uuid.UUID `json:"id"`
	MaterialID uuid.UUID `json:"material_id"`
	Title      string    `json:"title"`
	ImageKey   string    `json:"image_key"`
	ImageSize  int64     `json:"image_size"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) createImageFlashcard(ctx context.Context, arg createImageFlashcardParams) (ImageFlashcard, error) {
	row := q.db.QueryRowContext(ctx, createImageFlashcard,
		arg.ID,
		arg.MaterialID,
		arg.Title,
		arg.ImageKey,
		arg.ImageSize,
		arg.UserID,
	)
	var i ImageFlashcard
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Title,
		&i.ImageKey,
		&i.ImageSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsed,
	)
	return i, err
}
