// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image_labels.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const insertImageLabel = `-- name: insertImageLabel :one
INSERT INTO image_labels (id, image_id, x_start, x_end, y_start, y_end) 
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING image_labels.id, image_labels.image_id, image_labels.x_start, image_labels.x_end, image_labels.y_start, image_labels.y_end, image_labels.created_at, image_labels.updated_at
`

type insertImageLabelParams struct {
	ID      uuid.UUID `json:"id"`
	ImageID uuid.UUID `json:"image_id"`
	XStart  float64   `json:"x_start"`
	XEnd    float64   `json:"x_end"`
	YStart  float64   `json:"y_start"`
	YEnd    float64   `json:"y_end"`
}

func (q *Queries) insertImageLabel(ctx context.Context, arg insertImageLabelParams) (ImageLabel, error) {
	row := q.db.QueryRowContext(ctx, insertImageLabel,
		arg.ID,
		arg.ImageID,
		arg.XStart,
		arg.XEnd,
		arg.YStart,
		arg.YEnd,
	)
	var i ImageLabel
	err := row.Scan(
		&i.ID,
		&i.ImageID,
		&i.XStart,
		&i.XEnd,
		&i.YStart,
		&i.YEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
