// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lectures.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const archiveLecture = `-- name: ArchiveLecture :execrows
UPDATE lectures l
SET archived_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
FROM materials m
JOIN collections c ON c.id = m.collection_id
WHERE l.id = $1 AND l.material_id = m.id AND c.user_id = $2
`

type ArchiveLectureParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveLecture(ctx context.Context, arg ArchiveLectureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveLecture, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createLecture = `-- name: CreateLecture :exec
INSERT INTO lectures (id, material_id, title, file_key, file_size)
SELECT $1, $2, $3, $4, $5
WHERE EXISTS (
    SELECT 1
    FROM materials m
    JOIN collections c ON c.id = m.collection_id
    WHERE m.id = $2 AND c.user_id = $6
)
`

type CreateLectureParams struct {
	ID         uuid.UUID `json:"id"`
	MaterialID uuid.UUID `json:"material_id"`
	Title      string    `json:"title"`
	FileKey    string    `json:"file_key"`
	FileSize   int64     `json:"file_size"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateLecture(ctx context.Context, arg CreateLectureParams) error {
	_, err := q.db.ExecContext(ctx, createLecture,
		arg.ID,
		arg.MaterialID,
		arg.Title,
		arg.FileKey,
		arg.FileSize,
		arg.UserID,
	)
	return err
}

const deleteLecture = `-- name: DeleteLecture :execrows
DELETE FROM lectures l
USING materials m, collections c
WHERE l.id = $1 AND l.material_id = m.id
  AND m.collection_id = c.id
  AND c.user_id = $2
`

type DeleteLectureParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteLecture(ctx context.Context, arg DeleteLectureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLecture, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLectureByID = `-- name: GetLectureByID :one
SELECT l.id, l.material_id, l.title, l.file_key, l.file_size, l.created_at, l.updated_at, l.archived_at
FROM lectures l
JOIN materials m ON m.id = l.material_id
JOIN collections c ON c.id = m.collection_id
WHERE l.id = $1 AND c.user_id = $2
`

type GetLectureByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetLectureByID(ctx context.Context, arg GetLectureByIDParams) (Lecture, error) {
	row := q.db.QueryRowContext(ctx, getLectureByID, arg.ID, arg.UserID)
	var i Lecture
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Title,
		&i.FileKey,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listActiveLectures = `-- name: ListActiveLectures :many
SELECT l.id, l.material_id, l.title, l.file_key, l.file_size, l.created_at, l.updated_at, l.archived_at
FROM lectures l
JOIN materials m ON m.id = l.material_id
JOIN collections c ON c.id = m.collection_id
WHERE c.user_id = $1 AND l.archived_at IS NULL
ORDER BY l.created_at DESC, l.id DESC
LIMIT 20 OFFSET $2
`

type ListActiveLecturesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListActiveLectures(ctx context.Context, arg ListActiveLecturesParams) ([]Lecture, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLectures, arg.UserID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lecture
	for rows.Next() {
		var i Lecture
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.Title,
			&i.FileKey,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedLectures = `-- name: ListArchivedLectures :many
SELECT l.id, l.material_id, l.title, l.file_key, l.file_size, l.created_at, l.updated_at, l.archived_at
FROM lectures l
JOIN materials m ON m.id = l.material_id
JOIN collections c ON c.id = m.collection_id
WHERE c.user_id = $1 AND l.archived_at IS NOT NULL
ORDER BY l.created_at DESC, l.id DESC
LIMIT 20 OFFSET $2
`

type ListArchivedLecturesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListArchivedLectures(ctx context.Context, arg ListArchivedLecturesParams) ([]Lecture, error) {
	rows, err := q.db.QueryContext(ctx, listArchivedLectures, arg.UserID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lecture
	for rows.Next() {
		var i Lecture
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.Title,
			&i.FileKey,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLectures = `-- name: ListLectures :many
SELECT l.id, l.material_id, l.title, l.file_key, l.file_size, l.created_at, l.updated_at, l.archived_at
FROM lectures l
JOIN materials m ON m.id = l.material_id
JOIN collections c ON c.id = m.collection_id
WHERE c.user_id = $1
ORDER BY l.created_at DESC, l.id DESC
LIMIT 20 OFFSET $2
`

type ListLecturesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListLectures(ctx context.Context, arg ListLecturesParams) ([]Lecture, error) {
	rows, err := q.db.QueryContext(ctx, listLectures, arg.UserID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lecture
	for rows.Next() {
		var i Lecture
		if err := rows.Scan(
			&i.ID,
			&i.MaterialID,
			&i.Title,
			&i.FileKey,
			&i.FileSize,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveLecture = `-- name: UnarchiveLecture :execrows
UPDATE lectures l
SET archived_at = NULL, updated_at = CURRENT_TIMESTAMP
FROM materials m
JOIN collections c ON c.id = m.collection_id
WHERE l.id = $1 AND l.material_id = m.id AND c.user_id = $2
`

type UnarchiveLectureParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnarchiveLecture(ctx context.Context, arg UnarchiveLectureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unarchiveLecture, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLectureTitle = `-- name: UpdateLectureTitle :execrows
UPDATE lectures l
SET title = $3, updated_at = CURRENT_TIMESTAMP
FROM materials m
JOIN collections c ON c.id = m.collection_id
WHERE l.id = $1 AND l.material_id = m.id AND c.user_id = $2
`

type UpdateLectureTitleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

func (q *Queries) UpdateLectureTitle(ctx context.Context, arg UpdateLectureTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLectureTitle, arg.ID, arg.UserID, arg.Title)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
