// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveCollection(ctx context.Context, arg ArchiveCollectionParams) (int64, error)
	ArchiveLecture(ctx context.Context, arg ArchiveLectureParams) (int64, error)
	ArchiveMaterial(ctx context.Context, arg ArchiveMaterialParams) (int64, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) error
	CreateLecture(ctx context.Context, arg CreateLectureParams) error
	DeleteLecture(ctx context.Context, arg DeleteLectureParams) (int64, error)
	GetAllArchivedCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error)
	GetAllArchivedMaterialsInCollection(ctx context.Context, arg GetAllArchivedMaterialsInCollectionParams) ([]Material, error)
	GetAllCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error)
	GetAllMaterialsInCollection(ctx context.Context, arg GetAllMaterialsInCollectionParams) ([]Material, error)
	GetAllTokensByScope(ctx context.Context, arg GetAllTokensByScopeParams) ([]Token, error)
	GetAllTokensByUserID(ctx context.Context, userID uuid.UUID) ([]Token, error)
	GetAllUnarchivedCollections(ctx context.Context, userID uuid.UUID) ([]Collection, error)
	GetAllUnarchivedMaterialsInCollection(ctx context.Context, arg GetAllUnarchivedMaterialsInCollectionParams) ([]Material, error)
	GetArchivedCollectionByID(ctx context.Context, arg GetArchivedCollectionByIDParams) (Collection, error)
	GetCollectionByID(ctx context.Context, arg GetCollectionByIDParams) (Collection, error)
	GetLectureByID(ctx context.Context, arg GetLectureByIDParams) (Lecture, error)
	GetMaterialByID(ctx context.Context, arg GetMaterialByIDParams) (Material, error)
	GetSessionByHash(ctx context.Context, tokenHash string) (GetSessionByHashRow, error)
	GetTokenByHash(ctx context.Context, hash string) (Token, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserLibrary(ctx context.Context, userID uuid.UUID) ([]GetUserLibraryRow, error)
	InsertMaterial(ctx context.Context, arg InsertMaterialParams) error
	InsertToken(ctx context.Context, arg InsertTokenParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	ListActiveLectures(ctx context.Context, arg ListActiveLecturesParams) ([]Lecture, error)
	ListArchivedLectures(ctx context.Context, arg ListArchivedLecturesParams) ([]Lecture, error)
	ListLectures(ctx context.Context, arg ListLecturesParams) ([]Lecture, error)
	NewUserSession(ctx context.Context, arg NewUserSessionParams) error
	UnarchiveCollection(ctx context.Context, arg UnarchiveCollectionParams) (int64, error)
	UnarchiveLecture(ctx context.Context, arg UnarchiveLectureParams) (int64, error)
	UnarchiveMaterial(ctx context.Context, arg UnarchiveMaterialParams) (int64, error)
	UpdateCollectionDescription(ctx context.Context, arg UpdateCollectionDescriptionParams) (int64, error)
	UpdateCollectionTitle(ctx context.Context, arg UpdateCollectionTitleParams) (int64, error)
	UpdateLectureTitle(ctx context.Context, arg UpdateLectureTitleParams) (int64, error)
	UpdateMaterialTitle(ctx context.Context, arg UpdateMaterialTitleParams) (int64, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (int64, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (int64, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
	UseToken(ctx context.Context, hash string) (int64, error)
	verifyUserEmail(ctx context.Context, id uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
