// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, salt, created_at, verified_at, updated_at 
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	Email        string     `json:"email"`
	PasswordHash []byte     `json:"-"`
	Salt         []byte     `json:"-"`
	CreatedAt    time.Time  `json:"created_at"`
	VerifiedAt   *time.Time `json:"verified_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, salt, created_at, verified_at, updated_at 
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	Email        string     `json:"email"`
	PasswordHash []byte     `json:"-"`
	Salt         []byte     `json:"-"`
	CreatedAt    time.Time  `json:"created_at"`
	VerifiedAt   *time.Time `json:"verified_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Salt,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserLibrary = `-- name: GetUserLibrary :many
SELECT 
    c.id AS id,
    c.title AS title,
	c.description AS description,
    COALESCE(
        json_agg(
            json_build_object(
                'id', m.id,
                'title', m.title
            )
        ) FILTER (WHERE m.id IS NOT NULL), 
        '[]'
    )::jsonb AS materials 
FROM collections c
LEFT JOIN materials m ON m.collection_id = c.id
WHERE c.user_id = $1
GROUP BY c.id, c.title
ORDER BY c.created_at
`

type GetUserLibraryRow struct {
	ID          uuid.UUID       `json:"id"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Materials   json.RawMessage `json:"materials"`
}

func (q *Queries) GetUserLibrary(ctx context.Context, userID uuid.UUID) ([]GetUserLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserLibrary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserLibraryRow
	for rows.Next() {
		var i GetUserLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Materials,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, name, email, password_hash, salt)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"-"`
	Salt         []byte    `json:"-"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Salt,
	)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :execrows
UPDATE users
SET email = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserName = `-- name: UpdateUserName :execrows
UPDATE users
SET name = $1
WHERE id = $2
`

type UpdateUserNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserName, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $1, salt = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
`

type UpdateUserPasswordParams struct {
	PasswordHash []byte    `json:"-"`
	Salt         []byte    `json:"-"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.Salt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const verifyUserEmail = `-- name: verifyUserEmail :execrows
UPDATE users
SET verified_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) verifyUserEmail(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, verifyUserEmail, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
