// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const archiveCollection = `-- name: ArchiveCollection :execrows
UPDATE collections
SET archived_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND archived_at IS NULL
`

type ArchiveCollectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveCollection(ctx context.Context, arg ArchiveCollectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveCollection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCollection = `-- name: CreateCollection :execrows
INSERT INTO collections (id, user_id, title, description)
SELECT
    $1, $2, $3, $4
WHERE (
    SELECT COUNT(*)
    FROM collections
    WHERE user_id = $2
      AND archived_at IS NULL
) < 20
`

type CreateCollectionParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCollection,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllCollections = `-- name: GetAllCollections :many
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE user_id = $1
  AND archived_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllCollectionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetAllCollections(ctx context.Context, arg GetAllCollectionsParams) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getAllCollections, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedCollectionByID = `-- name: GetArchivedCollectionByID :one
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE id = $1
  AND user_id = $2
  AND archived_at IS NOT NULL
`

type GetArchivedCollectionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetArchivedCollectionByID(ctx context.Context, arg GetArchivedCollectionByIDParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getArchivedCollectionByID, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getArchivedCollections = `-- name: GetArchivedCollections :many
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE user_id = $1
  AND archived_at IS NOT NULL
ORDER BY archived_at DESC
LIMIT $2 OFFSET $3
`

type GetArchivedCollectionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetArchivedCollections(ctx context.Context, arg GetArchivedCollectionsParams) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getArchivedCollections, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, user_id, title, description, created_at, updated_at, archived_at
FROM collections
WHERE id = $1
  AND user_id = $2
  AND archived_at IS NULL
`

type GetCollectionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCollectionByID(ctx context.Context, arg GetCollectionByIDParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByID, arg.ID, arg.UserID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const unarchiveCollection = `-- name: UnarchiveCollection :execrows
UPDATE collections
SET archived_at = NULL
WHERE id = $1
  AND user_id = $2
  AND archived_at IS NOT NULL
`

type UnarchiveCollectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnarchiveCollection(ctx context.Context, arg UnarchiveCollectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unarchiveCollection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
