// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: materials.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const archiveMaterial = `-- name: ArchiveMaterial :execrows
UPDATE materials
SET archived_at = CURRENT_TIMESTAMP
WHERE materials.id = $1 
  AND materials.archived_at IS NULL
  AND EXISTS (
      SELECT 1 
      FROM collections 
      WHERE collections.id = materials.collection_id 
        AND collections.user_id = $2
  )
`

type ArchiveMaterialParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveMaterial(ctx context.Context, arg ArchiveMaterialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveMaterial, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllMaterialsInCollection = `-- name: GetAllMaterialsInCollection :many
SELECT 
    m.id, 
    m.collection_id, 
    m.title, 
    m.created_at, 
    m.updated_at, 
    m.archived_at
FROM materials m
JOIN collections c ON m.collection_id = c.id
WHERE c.user_id = $1 
  AND m.collection_id = $2
  AND m.archived_at IS NULL
`

type GetAllMaterialsInCollectionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	CollectionID uuid.UUID `json:"collection_id"`
}

func (q *Queries) GetAllMaterialsInCollection(ctx context.Context, arg GetAllMaterialsInCollectionParams) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, getAllMaterialsInCollection, arg.UserID, arg.CollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialByID = `-- name: GetMaterialByID :one
SELECT 
    m.id, 
    m.collection_id, 
    m.title, 
    m.created_at, 
    m.updated_at, 
    m.archived_at
FROM materials m
JOIN collections c ON m.collection_id = c.id
WHERE m.id = $1 
  AND c.user_id = $2
  AND m.archived_at IS NULL
`

type GetMaterialByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMaterialByID(ctx context.Context, arg GetMaterialByIDParams) (Material, error) {
	row := q.db.QueryRowContext(ctx, getMaterialByID, arg.ID, arg.UserID)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertMaterial = `-- name: InsertMaterial :exec
INSERT INTO materials (id, collection_id, title)
SELECT $1, $2, $3
WHERE (
    SELECT COUNT(*) 
    FROM materials 
    WHERE collection_id = $2
) < 20
AND EXISTS (
    SELECT 1 
    FROM collections 
    WHERE id = $2 AND user_id = $4
)
`

type InsertMaterialParams struct {
	ID           uuid.UUID `json:"id"`
	CollectionID uuid.UUID `json:"collection_id"`
	Title        string    `json:"title"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) InsertMaterial(ctx context.Context, arg InsertMaterialParams) error {
	_, err := q.db.ExecContext(ctx, insertMaterial,
		arg.ID,
		arg.CollectionID,
		arg.Title,
		arg.UserID,
	)
	return err
}

const unarchiveMaterial = `-- name: UnarchiveMaterial :execrows
UPDATE materials
SET archived_at = NULL
WHERE materials.id = $1 
  AND materials.archived_at IS NOT NULL
  AND EXISTS (
      SELECT 1 
      FROM collections 
      WHERE collections.id = materials.collection_id 
        AND collections.user_id = $2
  )
`

type UnarchiveMaterialParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnarchiveMaterial(ctx context.Context, arg UnarchiveMaterialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unarchiveMaterial, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
