// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID         uuid.UUID    `json:"id"`
	TokenHash  string       `json:"token_hash"`
	UserID     uuid.UUID    `json:"user_id"`
	DeviceName string       `json:"device_name"`
	CsrfHash   string       `json:"csrf_hash"`
	CreatedAt  time.Time    `json:"created_at"`
	LastUsedAt time.Time    `json:"last_used_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	Name         string     `json:"name"`
	IsSuspended  bool       `json:"is_suspended"`
	PasswordHash []byte     `json:"-"`
	Salt         []byte     `json:"-"`
	VerifiedAt   *time.Time `json:"verified_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
