// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error)
}

var _ Querier = (*Queries)(nil)
