// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetSessionByHash(ctx context.Context, tokenHash string) (GetSessionByHashRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
	NewUserSession(ctx context.Context, arg NewUserSessionParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
