// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, token_hash, csrf_hash, device_name, last_used_at, revoked_at
FROM sessions
WHERE token_hash = $1
`

type GetSessionByHashRow struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	TokenHash  string       `json:"token_hash"`
	CsrfHash   string       `json:"csrf_hash"`
	DeviceName string       `json:"device_name"`
	LastUsedAt time.Time    `json:"last_used_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
}

func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash string) (GetSessionByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByHash, tokenHash)
	var i GetSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.DeviceName,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const newUserSession = `-- name: NewUserSession :exec
INSERT INTO sessions(id, user_id, token_hash, device_name, csrf_hash)
VALUES($1, $2, $3, $4, $5)
`

type NewUserSessionParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	TokenHash  string    `json:"token_hash"`
	DeviceName string    `json:"device_name"`
	CsrfHash   string    `json:"csrf_hash"`
}

func (q *Queries) NewUserSession(ctx context.Context, arg NewUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, newUserSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceName,
		arg.CsrfHash,
	)
	return err
}
